name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        # Test the Java LTS versions and latest version available
        java-version: [11, 17]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK $
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}
      - name: Test with Maven
        run: ./gradlew build
